#!/bin/bash

get_active_window_title() {
  if command -v xdotool >/dev/null; then
    xdotool getactivewindow getwindowname
  else
    # temp
    mac_active_window_title
  fi
}

find_vim_pid() {
    command -v ggrep >/dev/null && command_grep="ggrep" || command_grep="grep"

    pid=$(get_active_window_title | "${command_grep}" -Po '(?<=\[)\d+(?=\])')

    [ -z "${pid}" ] && printf "No active shell found.\n" 1>&2 && exit 1
    printf "%s\n" "${pid}"
}

vim_launch() {
    NVIM_LISTEN_ADDRESS="/tmp/vim-${$}" exec nvim "$@"
}

vim_remote() {
    vim_pid=$(find_vim_pid)
    [ -z "${vim_pid}" ] && return

    nvr --servername "/tmp/vim-${vim_pid}" --nostart "$@"
}

if [ "$1" = "launch" ]; then
    shift
    vim_launch "$@"
elif [ "$1" = "remote" ]; then
    shift
    vim_remote "$@"
else
    find_vim_pid
fi
