#!/bin/bash

find_vim_pid() {
    pid=$(xdotool getactivewindow getwindowname | grep -Po '(?<=\[)\d+(?=\])')

    [ -z "${pid}" ] && printf "No active shell found.\n" 1>&2 && exit 1
    printf "%s\n" "${pid}"
}

vim_launch() {
    NVIM_LISTEN_ADDRESS="/tmp/vim-${$}" exec nvim "$@"
}

vim_remote() {
    vim_pid=$(find_vim_pid)
    [ -z "${vim_pid}" ] && return

    nvr --servername "/tmp/vim-${vim_pid}" --nostart "$@"
}

if [ "$1" = "launch" ]; then
    shift
    vim_launch "$@"
elif [ "$1" = "remote" ]; then
    shift
    vim_remote "$@"
else
    find_vim_pid
fi
